---
title: "hw-02"
author: "Andrew Thomson (S2138243)"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)
edibnb <- read_csv("data/edibnb.csv")
council <- read_csv("data/council_assessments.csv")
```


### Exercise 1

```{r hw2-ex1}
edibnb %>%
select(id, review_scores_rating, number_of_reviews) %>%
filter(review_scores_rating == "100") %>%
  arrange(desc(number_of_reviews)) %>%
  slice(1)

```


ID 860170

### Exercise 2

```{r hw2-ex2}
edibnb %>%
select(price, neighbourhood, accommodates) %>%
filter(neighbourhood == "Southside",
       accommodates >= "4") %>%
summarise(minimum_price = min(price),
          maximum_price = max(price),
          average_price = mean(price))

```


_Remove this text, and add your answer for Exercise 2 here._

### Exercise 3

```{r hw2-ex3}
edibnb %>%
mutate(number_of_bathrooms = ceiling(bathrooms)) %>%
select(number_of_bathrooms, bedrooms) %>%
filter(number_of_bathrooms > bedrooms) %>%
count(no_rows = TRUE)

```


_Remove this text, and add your answer for Exercise 3 here._

### Exercise 4

```{r hw2-ex4}


```


_Remove this text, and add your answer for Exercise 4 here._

### Exercise 5

```{r hw2-ex5}
# remove this comment and add the code for Exercise 5 here

```


_Remove this text, and add your answer for Exercise 5 here._

